# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/ENGS31_S23/VGA/VGA.srcs/sources_1/ip/bitmaps/bitmaps.xci
# IP: The module: 'bitmaps' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ENGS31_S23/VGA/VGA.gen/sources_1/ip/bitmaps/bitmaps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitmaps'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: o:/ENGS31_S23/VGA/VGA.srcs/sources_1/ip/bitmaps/bitmaps.xci
# IP: The module: 'bitmaps' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ENGS31_S23/VGA/VGA.gen/sources_1/ip/bitmaps/bitmaps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bitmaps'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
